<?php

namespace IqitElementor\Helper;

/**
 * Detects whether a decoded Elementor layout was generated by the current
 * iqitelementor module or by the legacy IQIT-Commerce module shipped under
 * `iqitelementor_legacy`.
 *
 * Detection order:
 *
 *   1. Owner signature envelope → current (unambiguous, the current module
 *      stamped this payload itself).
 *   2. Current-only setting keys (`_section_custom_css`, `_custom_css`,
 *      `_custom_css_title`, `_custom_css_description`) anywhere in the tree →
 *      current. These keys are emitted on every element by the current
 *      schema and never existed in the legacy module, so they reliably
 *      identify pre-signature content saved by the current module.
 *   3. Legacy-only setting keys → legacy.
 *   4. Otherwise → current (default for ambiguous payloads).
 *
 * The two modules write to the same DB columns; only the JSON shape differs.
 * Two legacy-only setting keys are used as signatures (any one is enough):
 *
 *   - section.settings.slider_section_navigation (legacy slider group, replaced
 *                                                in the current module by
 *                                                `dots` / `arrows` / `scrollbar`)
 *   - widget(heading).settings.header_style     (removed from current Heading,
 *                                                which uses `heading_style`
 *                                                with an `ing` — different key)
 *
 * NOTE: `column.settings.screen_sm` is NOT a reliable signal even though it is
 * legacy-only at the schema level: the editor's JS Backbone model preserves
 * unknown keys on save (passthrough), so columns originally created in the
 * legacy module retain `screen_sm` after being re-saved through the current
 * editor — leading to false positives. The `header_style` and
 * `slider_section_navigation` keys do not survive a current-editor save
 * because the current schema uses different key names entirely (not just a
 * dropped control), so they remain reliable signatures of legacy authorship.
 *
 * Note: a legacy layout re-saved through the current editor will lose these
 * keys (they aren't reserialized), so it is correctly classified as `current`
 * after an edit. That is the intended behaviour.
 */
class FormatDetector
{
    public const VERSION_LEGACY = 'legacy';
    public const VERSION_CURRENT = 'current';

    /**
     * Returns true if the decoded payload carries the current iqitelementor
     * owner signature. Takes priority over legacy heuristics: any payload the
     * current module has persisted is unambiguously ours, regardless of what
     * leaked in from the editor's Backbone passthrough.
     *
     * @param array<mixed, mixed> $payload Either the wrapped envelope or a bare elements array.
     */
    public static function hasOwnerSignature(array $payload): bool
    {
        return OwnerSignature::hasSignature($payload);
    }

    /**
     * @param array<mixed, mixed> $payload Either the wrapped envelope or a bare elements array.
     */
    public static function isLegacy(array $payload): bool
    {
        if (self::hasOwnerSignature($payload)) {
            return false;
        }

        $elements = OwnerSignature::unwrap($payload);

        if (self::scanCurrentMarkers($elements)) {
            return false;
        }

        return self::scan($elements);
    }

    /**
     * @param array<mixed, mixed> $payload Either the wrapped envelope or a bare elements array.
     */
    public static function detect(array $payload): string
    {
        if (self::hasOwnerSignature($payload)) {
            return self::VERSION_CURRENT;
        }

        $elements = OwnerSignature::unwrap($payload);

        if (self::scanCurrentMarkers($elements)) {
            return self::VERSION_CURRENT;
        }

        return self::scan($elements) ? self::VERSION_LEGACY : self::VERSION_CURRENT;
    }

    /**
     * Positive detection: the current iqitelementor schema added the
     * `_custom_css*` group (`_section_custom_css`, `_custom_css_title`,
     * `_custom_css`, `_custom_css_description`) on every element. Those
     * keys never existed in the legacy IQIT-Commerce module, so finding
     * any of them on any node is unambiguous proof of current authorship,
     * even when the owner signature envelope is absent (pre-signature
     * content saved by the current module).
     *
     * @param array<mixed, mixed> $nodes
     */
    private static function scanCurrentMarkers(array $nodes): bool
    {
        foreach ($nodes as $node) {
            if (!is_array($node)) {
                continue;
            }

            $settings = isset($node['settings']) && is_array($node['settings']) ? $node['settings'] : [];

            if (array_key_exists('_section_custom_css', $settings)
                || array_key_exists('_custom_css', $settings)
                || array_key_exists('_custom_css_title', $settings)
                || array_key_exists('_custom_css_description', $settings)) {
                return true;
            }

            if (!empty($node['elements']) && is_array($node['elements']) && self::scanCurrentMarkers($node['elements'])) {
                return true;
            }
        }

        return false;
    }

    /**
     * @param array<mixed, mixed> $nodes
     */
    private static function scan(array $nodes): bool
    {
        foreach ($nodes as $node) {
            if (!is_array($node)) {
                continue;
            }

            $type = isset($node['elType']) ? (string) $node['elType'] : '';
            $settings = isset($node['settings']) && is_array($node['settings']) ? $node['settings'] : [];

            if ($type === 'section' && array_key_exists('slider_section_navigation', $settings)) {
                return true;
            }
            if ($type === 'widget'
                && (isset($node['widgetType']) && $node['widgetType'] === 'heading')
                && array_key_exists('header_style', $settings)) {
                return true;
            }

            if (!empty($node['elements']) && is_array($node['elements']) && self::scan($node['elements'])) {
                return true;
            }
        }

        return false;
    }
}
